# -*- mode: ruby -*-
# vi: set ft=ruby :

#Установка переменной окружения, задающей российское зеркало для box-файлов
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'


Vagrant.configure("2") do |config|

  # Создание виртуальной машины веб-сервера
  config.vm.define "webserver" do |web|
    web.vm.box = "bento/ubuntu-24.04"
    web.vm.network "private_network", ip: "192.168.50.10"
  
    # Установка пакетов
    web.vm.provision "shell", inline: <<-SHELL
    
      # Установка Apache
      sudo apt-get update
      sudo apt-get install apache2 -y
      sudo systemctl enable apache2

      # Установка клиента mysql
      sudo apt-get install -y mysql-client

      # Установка модуля PHP
      sudo apt install php libapache2-mod-php php-mysql -y
      sudo systemctl restart apache2
    SHELL

    # Настройка модуля PHP
    web.vm.provision "shell", path: "provision/wb_setup.sh"
  end


  # Создание виртуальной машины базы данных
  config.vm.define "dbserver" do |db|
    db.vm.box = "bento/ubuntu-24.04"
    db.vm.network "private_network", ip: "192.168.50.11"

    # Копируем файл SQL-скрипта на виртуальную машину
    db.vm.provision "file", source: "provision/db_setup.sql", destination: "/tmp/db_setup.sql"
  
    # Настройка MySQL
    db.vm.provision "shell", inline: <<-SHELL

      # Установка MySQL
      sudo apt-get update
      sudo apt-get install -y mysql-server
      sudo systemctl enable mysql

      # Выполнение SQL-скрипта
      sudo mysql -u root < /tmp/db_setup.sql    
    SHELL

    # Изменение области видимости сервера MySQL через sh-скрипт
    db.vm.provision "shell", path: "provision/db_setup.sh"
  end


  # Создание виртуальной машины балансировщика нагрузки
  config.vm.define "loadbalancer" do |lb|
    lb.vm.box = "bento/ubuntu-24.04"
    lb.vm.network "public_network"
    
    # Установка HAProxy
    lb.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y haproxy
      sudo systemctl enable haproxy
    SHELL

    # Настройка балансировщика нагрузки через sh-скрипт
    lb.vm.provision "shell", path: "provision/lb_setup.sh"
  end
end
